// Make an app that stores marks, calculates grades and  gets top students
// Store the name and marks of students using a map
var students = {'Ken': 34, 'Ben': 79, 'Vad': 67, 'Mary': 95, 'Jane': 27};

// Grade conversion function
void grader(score, name) {
  switch (score) {
    case >= 90:
      print('$name scored $score which is grade A');
      break;
    case >= 80:
      print(' $name scored $score which is grade B');
      break;
    case >= 70:
      print('$name scored $score which is grade C');
      break;
    case >= 60:
      print('$name scored $score which is grade D');
      break;
    case < 60:
      print('$name scored $score which is grade E');
      break;
    default:
      print('$name not graded!!!!!!!');
  }
}

void main() {
  // loop through the students to get name and marks of each student
  int total = 0;
  for (var entry in students.entries) {
    // getting the total of the scores
    total += entry.value;
    grader(entry.value, entry.key);
  }

  // Calculating average using the total of the scores and the number of students
  // then print output
  int number = students.length;
  double avg = total / number;
  print('The average mark of the class is: $avg');

  // finding the top students
  // if score is greater than average we print
  for (var entry in students.entries) {
    if (entry.value > avg) {
      print('Top student: ${entry.key}');
    }
  }
}

// Just completed my first  50 lines of code without it being generated by AI
// More practice more practice and consistency